In [1]:
import torch 
import numpy as np

In [3]:
tensor_a = torch.tensor([0,1,2,3,4])
tensor_b = torch.tensor([5,6,7,8,9])
print(tensor_a)
print(tensor_b)

tensor([0, 1, 2, 3, 4])
tensor([5, 6, 7, 8, 9])


In [4]:
# ADDITION Shorthand form 
tensor_a + tensor_b 

tensor([ 5,  7,  9, 11, 13])

In [5]:
# ADDITION Long form 
# I feel like this approach is definitely more expressive and clearly shows that tensors are being worked upon. 
torch.add(tensor_a , tensor_b)

tensor([ 5,  7,  9, 11, 13])