In [1]:
import torch 
import numpy as np

In [3]:
tensor_a = torch.tensor([0,1,2,3,4])
tensor_b = torch.tensor([5,6,7,8,9])
print(tensor_a)
print(tensor_b)

tensor([0, 1, 2, 3, 4])
tensor([5, 6, 7, 8, 9])


In [4]:
# ADDITION Shorthand form 
tensor_a + tensor_b 

tensor([ 5,  7,  9, 11, 13])

In [5]:
# ADDITION Long form 
# I feel like this approach is definitely more expressive and clearly shows that tensors are being worked upon. 
torch.add(tensor_a , tensor_b)

tensor([ 5,  7,  9, 11, 13])

In [6]:
# SUBTRACTION Shorthand form 
tensor_b - tensor_a 

tensor([5, 5, 5, 5, 5])

In [7]:
# SUBTRACTION Long form 
torch.sub(tensor_b, tensor_a) # could also use .subtract()

tensor([5, 5, 5, 5, 5])

In [9]:
# MULTIPLICATION short form 
tensor_a * tensor_b

tensor([ 0,  6, 14, 24, 36])

In [10]:
# MULTIPLICATION long form 
torch.mul(tensor_a, tensor_b)

tensor([ 0,  6, 14, 24, 36])

In [11]:
# DIVISION short form 
tensor_b / tensor_a 

tensor([   inf, 6.0000, 3.5000, 2.6667, 2.2500])

In [12]:
# DIVISION long form 
torch.div(tensor_b, tensor_a)

tensor([   inf, 6.0000, 3.5000, 2.6667, 2.2500])

In [14]:
# REMAINDER short form 
# tensor_b % tensor_a # ZeroDivisionError
tensor_a % tensor_b 

tensor([0, 1, 2, 3, 4])

In [15]:
# REMAINDER long form 
torch.remainder(tensor_a, tensor_b) 

tensor([0, 1, 2, 3, 4])

In [16]:
# EXPONENT short form 
tensor_b ** tensor_a

tensor([   1,    6,   49,  512, 6561])

In [17]:
# EXPONENT long form 
torch.pow(tensor_b, tensor_a) 

tensor([   1,    6,   49,  512, 6561])